version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/back"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
