sonar.organization=bhahlou
sonar.projectKey=Bhahlou_P7-FSJA
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=**/*Test*.java,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.png,front/src/**/*.jpg,front/src/**/*.jpeg,front/src/**/*.ico,front/src/**/*.gif,front/src/**/*.woff,front/src/**/*.woff2,front/src/**/*.ttf

sonar.java.binaries=back/build/classes/java/main
sonar.java.test.binaries=back/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info
